import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import tailwindcss from "tailwindcss";
import autoprefixer from "autoprefixer";

export default defineConfig({
    plugins: [
        laravel({
            postcss: [tailwindcss(), autoprefixer()],
            input: [
                'resources/css/app.scss',
                'resources/js/app.tsx',
                'resources/css/ex-autocomplete.scss',
                'resources/css/experiment-expicker.scss',
                'resources/css/experiment-exbox.scss',
                'resources/css/sweetalert-custom.css',
                'resources/css/tagify-custom.css',
                'resources/css/experiment-exmenu.scss',
                'resources/css/main/hrd/on-boarding/custom.css',
                'resources/css/main/hrd/recruitment/custom.css',
                'resources/css/main/hrd/recruitment/details/styles.css',
                'resources/js/login/index.tsx',
                'resources/js/main/hrd/on-boarding/main.ts',
                'resources/js/main/hrd/recruitment/main.ts',
                'resources/js/main/hrd/recruitment/details/kanbanHandlers.ts',
                'resources/js/main/hrd/data-employee/index.tsx',
                'resources/js/main/hrd/data-employee/create.tsx',
                'resources/js/main/hrd/data-employee/detail.tsx',
                'resources/js/main/hrd/data-employee/bulk-upload.tsx',
                'resources/js/main/training/data/main.ts',
                'resources/js/main/training/request/main.ts',
                'resources/js/main/time/scheduler/index.tsx',
                'resources/js/main/time/attendance/index.tsx',
                'resources/js/main/time/request/attendance/index.tsx',
                'resources/js/main/time/request/leave/index.tsx',
                'resources/js/main/time/request/overtime/index.tsx',
                'resources/js/main/payrolls/data-payroll-components/create.tsx',
                'resources/js/main/payrolls/data-payroll-components/update.tsx',
                'resources/js/main/payrolls/data-payroll-process/index.tsx',
                'resources/js/main/payrolls/data-payroll-process/create.tsx',
                'resources/js/main/payrolls/data-payroll-reports/data-salary/index.tsx',
                'resources/js/main/finance/data-loan/index.tsx',
                'resources/js/main/finance/data-loan/create.tsx',
                'resources/js/main/finance/data-loan/update.tsx',
                'resources/js/main/finance/data-reimbursement/data-assignment/process.tsx',
                'resources/js/main/finance/data-reimbursement/data-request/index.tsx',
                'resources/js/main/finance/data-reimbursement/data-request/create.tsx',
                'resources/js/main/finance/data-reimbursement/data-request/detail.tsx',
                'resources/js/main/finance/data-reimbursement/data-request/update.tsx',
                'resources/js/main/companies/data-company/index.tsx',
                'resources/js/main/companies/data-work-location/index.tsx',
                'resources/js/main/companies/data-department/index.tsx',
                'resources/js/main/companies/data-designation/index.tsx',
                'resources/js/main/master/data-assets-type/index.tsx',
                'resources/js/main/master/data-assets/index.tsx',
                'resources/js/main/master/data-blood-type/index.tsx',
                'resources/js/main/master/data-bank/index.tsx',
                'resources/js/main/settings/payroll/data-absence/index.tsx',
                'resources/js/main/settings/payroll-components/data-allowance/index.tsx',
                'resources/js/main/settings/payroll-components/data-deduction/index.tsx',
                'resources/js/main/settings/payroll-components/data-insurance/index.tsx',
                'resources/js/main/settings/payroll/data-payment-schedule/index.tsx',
                'resources/js/main/settings/data-finance-management/data-reimbursement/index.tsx',
                'resources/js/main/settings/data-finance-management/data-reimbursement/process.tsx',
                'resources/js/main/settings/data-time-management/data-time-shift/index.tsx',
                'resources/js/main/settings/data-time-management/data-time-schedule/index.tsx',
                'resources/js/main/settings/data-time-management/data-time-schedule/create.tsx',
                'resources/js/main/settings/data-time-management/data-time-schedule/update.tsx',
                'resources/js/main/settings/data-time-management/data-time-leave/index.tsx',
                'resources/js/main/settings/data-time-management/data-time-leave/create.tsx',
                'resources/js/main/settings/data-time-management/data-time-holiday/index.tsx',
                'resources/js/main/settings/data-roles/index.tsx',
                'resources/js/main/settings/change-password/index.tsx',
                'resources/js/main/hrd/on-boarding/main.ts',
                'resources/js/main/hrd/on-boarding/checkboxHandlers.ts',
                'resources/js/main/hrd/on-boarding/deleteButtonHandlers.ts',
                'resources/js/main/hrd/on-boarding/dropzoneHandlers.ts',
                'resources/js/main/hrd/on-boarding/dynamicFormHandlers.ts',
                'resources/js/main/hrd/on-boarding/modalHandlers.ts',
                'resources/js/main/hrd/on-boarding/multiSelectHandlers.ts',
                'resources/js/main/hrd/on-boarding/paginationHandlers.ts',
                'resources/js/main/hrd/on-boarding/stepsHandlers.ts',
                'resources/js/main/hrd/on-boarding/tableHandlers.ts',
                'resources/js/main/hrd/recruitment/main.ts',
                'resources/js/main/hrd/recruitment/checkBoxHandlers.ts',
                'resources/js/main/hrd/recruitment/deleteButtonHandlers.ts',
                'resources/js/main/hrd/recruitment/modalHandlers.ts',
                'resources/js/main/hrd/recruitment/multiSelectHandlers.ts',
                'resources/js/main/hrd/recruitment/populateOptions.ts',
                'resources/js/main/hrd/recruitment/stepsHandlers.ts',
                'resources/js/main/hrd/recruitment/tabHandlers.ts',
                'resources/js/main/hrd/recruitment/public-form/recruitment.ts',
                'resources/js/main/hrd/recruitment/public-form/stepsHandlers.ts',
                'resources/js/main/hrd/recruitment/public-form/submitHandlers.ts',
                'resources/css/main/hrd/recruitment/public-form/styles.css',
                'resources/js/main/hrd/recruitment/utility/createRecruitmentHandlers.ts',
                'resources/js/main/hrd/recruitment/utility/hiringProcess.ts',
                'resources/js/main/hrd/recruitment/utility/question.ts',
                'resources/css/main/hrd/recruitment/details/styles.css',
                'resources/js/main/hrd/manpower-planning/modalHandlers.ts',
                'resources/js/main/hrd/manpower-planning/main.ts',
                'resources/js/main/hrd/manpower-planning/populateOption.ts',
                'resources/css/main/hrd/manpower-planning/custom.css',
                'resources/js/main/hrd/recruitment/details/main.ts',
            ],
            refresh: true,
        }),
    ],
    build: {
        chunkSizeWarningLimit: 1600,
    },
    server: {
        host: '0.0.0.0', 
        port: 5175,
        hmr: {
            protocol: 'ws',
            host: 'localhost',
        },
    },
    resolve: {
        alias: {
            '@': '/resources',
        },
    },
});
